### PR TITLE
Add L5 support

### PR DESCRIPTION
**Pull request by gezedo**
This is an alpha for L5 support, not extensively tested, work is still in progress.
Successfully connects to L552ZET from eval ST eval board. Write not tested.
Only cares about non secure accesses for the time being.

### CODE REVIEW

**Comment by Nightwalker-87** [comment]
Any update on this?

**Comment by gezedo-tandem** [comment]
As far as I can tell, it can read and write the Flash. Debug though GDB server did not work as I expected.
Further development from me are on hold.
Hope it can help, even in that early state.

**Comment by gezedo** [comment]
As far as I can tell, it can read and write the Flash. Debug though GDB server did not work as I expected.
Further development from me are on hold.
Hope it can help, even in that early state.

**Comment by Nightwalker-87** [comment]
@grevaillot: Can you help out with this?

**Review by Nightwalker-87 — APPROVED** [review]

**Comment by Nightwalker-87** [comment]
Can someone with appropiate hardware please verify if this feature is working properly?

**Pull request merged**
