### PR TITLE
[doc] Fixed broken links

### PR DESCRIPTION
**Pull request by gemesa**
Found some broken links while reading the docs and fixed them.

### CODE REVIEW

**Comment by slyshykO** [comment]
@Nightwalker-87 
I think that **supported devices.md** should be renamed to **supported_devices.md** 
Names with spaces still add more issues than they should.

**Comment by gemesa** [comment]
Right, if you rename it you can remove the angle brackets also:
`[supported devices.md](<doc/supported devices.md>) --> [supported_devices.md](doc/supported_devices.md)`

**Comment by Nightwalker-87** [comment]
> Right, if you rename it you can remove the angle brackets also: `[supported devices.md](<doc/supported devices.md>) --> [supported_devices.md](doc/supported_devices.md)`

Yes, we'll do that. Can you update that in this PR directly?

**Comment by gemesa** [comment]
> > Right, if you rename it you can remove the angle brackets also: `[supported devices.md](<doc/supported devices.md>) --> [supported_devices.md](doc/supported_devices.md)`
> 
> @gemesa Yes, we should do that. Can you update this PR directly?

Renamed it, please review it

**Review by Nightwalker-87 — APPROVED** [review]

**Review by Nightwalker-87 — APPROVED** [review]

**Pull request merged**
