### PR TITLE
[feature] support STM32F4 option bytes

### PR DESCRIPTION
**Pull request by timothytylee**
Allow the option bytes to be read/written to STM32F4.  Tested on a STM32F405.

### CODE REVIEW

**Comment by Ant-ON** [comment]
@timothytylee how view from the already written code, the STM32_XX_OPTION_BYTES_BASE constants use the physical address of option bytes. For STM32F4 it is 0x1FFFC000 (dm00031020, p. 88)

**Comment by timothytylee** [comment]
Yet in section 3.7.2 (pg92), it says to use FLASH_OPTCR register to program the user option bytes.  I have checked that the RDP feature does indeed come into effect after changing the FLASH_OPTCR.  The values read back from 0x1fffc000 appear to be some random bytes.

**Comment by Ant-ON** [comment]
@timothytylee You're right

**Comment by Nightwalker-87** [comment]
Are we ready yet?

**Review by Nightwalker-87 — APPROVED** [review]

**Comment by Nightwalker-87** [comment]
@timothytylee Does this close any open issues?

**Comment by timothytylee** [comment]
@Nightwalker-87 this is a new feature.  I do not think there are issues related to it.

**Pull request merged**
