### PR TITLE
Update for package distribution

### LINKED ISSUE #738: [install] Windows binary is configured to a hard-coded path
When using the latest (1.3.0) windows binary release, the path seems to be hard-coded. When running st-util.exe in cmd, the output is "C:\Users\Jerry\Desktop\st-util.exe not found". The file is located at C:\stlink\st-util.exe instead.

### LINKED ISSUE #795: [doc] Windows binary installation instructions?
Given, particularly, the problem raised in #738, it seems there is probably only one correct way to install the current binary for Windows (v1.3.0).

However, as far as I can see, there are no instructions or guidelines on how to do that.

Please explain the steps required, and document them somewhere they will be seen, when trying to install it.

At the moment, it just says this:

**Installation

Windows users can download v1.3.0 from the releases page.**

but the binary contains no further information on what to do to install it, and neither does the downloads page.

### PR DESCRIPTION
**Pull request by Nightwalker-87**
Changes & additions:

- New cpack package-config for DEB and RPM
- Toolchain file for cross-building
- Script to automate MinGW cross-building
- Added file headers for .cmake files
- Added dpkg and rpm to required pkgs
- Removed deprecated debian pkg config settings
- Update for travis build configuration:
--> Added builds for clang -m32 on arch: AMD64
--> Corrected invalid config settings
--> Added clang-9 builds for linux
--> Moved scripts to root directory
--> Added MinGW cross-test-build for linux
- Updated steps for release preparation
- Changed destination for binary archives
- Added note on windows binary installation (Closes #738) (Closes #795)
- Contributors now listed in separate file
- Added version info for static library
- Added package changelog files for deb & rpm
- Added license & rules file for deb pkg
- Removed unneeded commands in travis.sh
- Removed -Wno-dev flag in Release target
- cmake: Grouped udev and modprobe.d config
- rpm package now relocatable (CPackRPM)
- Tidy up install paths & directories:
-> modprobe.d & udev rules (both are now ON per default on Linux)
-> stlink-gui supplements
-> man pages
- Fixed paths according to GNUInstallDirs
- cmake: Restructured library config
- Test files & gui now use shared library

### CODE REVIEW

**Comment by Nightwalker-87** [comment]
> It is Ok for me

Wait - it's not ready yet ... :eyes:

**Comment by slyshykO** [comment]
> Wait - it's not ready yet ...

Something else planned?

**Comment by Nightwalker-87** [comment]
Only some minor fixes, that's why I opened a draft PR.

**Comment by Nightwalker-87** [comment]
As @slyshykO reported, there is still an issue with a static link to libssp on Windows which is not as expected. This needs a fix.

**Comment by Nightwalker-87** [comment]
Can someone else also look into this please?

**Comment by Nightwalker-87** [comment]
As @slyshykO reported, there is still an issue with a static linking to libssp on Windows when the binary package is generated via a debian cross-build which is not as expected. This needs a fix.

When building natively on Windows this issue does not occur, as I could verify by myself on a virtual machine. As of the current state of knowledge I can't make out any difference in the related cmake compilation routine in `CMakeLists.txt`.

If the reason is not found and nobody else is going to show any interest in this, cross-building for Windows will only generate non-functional binaries and thus will be useless...

**Comment by Nightwalker-87** [comment]
@chenguokai: Can we use the shared st-link library on macOS instead of the static one or would we run into errors with this even though we have a package-based subsystem present that deeply integrates (Macports or Homebrew)? Would there be a way to make it work? Is ssp needed as well? I can't completely figure out the sense of the current settings apart from the need for a static lib on windows where a stand alone binary is desirable.

**Comment by Nightwalker-87** [comment]
@Vascom: How can we make the rpm package relocatable (universal)? I found there are still a few minor issues related to this for our rpm package:

```
CPack: Create package
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/Internal/CPack/CPackRPM.cmake:140 (message):
  CPackRPM:Warning: Path
  [$PATH_TO_FILE$]
  is not on one of the relocatable paths! Package will be partially
  relocatable.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/Internal/CPack/CPackRPM.cmake:1008 (cpack_rpm_prepare_relocation_paths)
  /usr/share/cmake-3.16/Modules/Internal/CPack/CPackRPM.cmake:1879 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CPackRPM: Will use GENERATED spec file: /$USER-PATH$/stlink/build/Debug/_CPack_Packages/Linux/RPM/SPECS/stlink.spec
```
This relates to the following files:

  /$USER-PATH$/stlink/build/Debug/install/etc/modprobe.d/stlink_v1.conf
  /$USER-PATH$/stlink/build/Debug/install/etc/udev/rules.d/49-stlinkv1.rules
  /$USER-PATH$/stlink/build/Debug/install/etc/udev/rules.d/49-stlinkv2-1.rules
  /$USER-PATH$/stlink/build/Debug/install/etc/udev/rules.d/49-stlinkv2.rules
  /$USER-PATH$/stlink/build/Debug/install/etc/udev/rules.d/49-stlinkv3.rules
  /$USER-PATH$/stlink/build/Debug/install/include/stlink.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/backend.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/chipid.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/commands.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/flash_loader.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/reg.h
  /$USER-PATH$/stlink/build/Debug/install/include/stlink/version.h
  /$USER-PATH$/stlink/build/Debug/install/include/stm32.h
  /$USER-PATH$/stlink/build/Debug/install/lib/libstlink.a
  /$USER-PATH$/stlink/build/Debug/install/lib/libstlink.so
  /$USER-PATH$/stlink/build/Debug/install/lib/libstlink.so.1
  /$USER-PATH$/stlink/build/Debug/install/lib/libstlink.so.1.6.0
  /$USER-PATH$/stlink/build/Debug/install/share/man/man1/st-flash.1
  /$USER-PATH$/stlink/build/Debug/install/share/man/man1/st-info.1
  /$USER-PATH$/stlink/build/Debug/install/share/man/man1/st-util.1

Do you or anyone else have an idea? It would be a nice to have, I think.

**Comment by Vascom** [comment]
Why do you need relocatable rpm?

**Comment by Nightwalker-87** [comment]
> Why do you need relocatable rpm?

It should install on various rpm-based distributions.

**Comment by Vascom** [comment]
As I see:
```
If this variable is set to TRUE or ON CPackRPM will try to build a relocatable RPM package. A relocatable RPM may be installed using:

rpm --prefix or --relocate
in order to install it at an alternate place see rpm(8).
```
Also seems it is only for debug subpackage.

**Comment by Nightwalker-87** [comment]
> Also seems it is only for debug subpackage.

No, this also applies to the release target, I only didn't want do paste duplicated output.

**Comment by Vascom** [comment]
It is bad idea to have one rpm package for many distros. All of them has differencies and this work should be done by maintrainers.

**Comment by Nightwalker-87** [comment]
Well they can do as they like, but I am not willing to generate several rpm packages for a project release. Thus this package should be widely deployable.

**Comment by Vascom** [comment]
You can not generate any.

**Comment by Nightwalker-87** [comment]
> You can not generate any.

We already do with cmake ;-)

**Comment by Nightwalker-87** [comment]
@slyshykO @chenguokai: These were the outstanding changes still missing to conclude this PR.
Now this static linking of libssp is the last nut to crack...

**Comment by Vascom** [comment]
> > You can not generate any.
> 
> We already do - with cmake ;-)

I mean do it properly as every distro recommend and require.

**Comment by Nightwalker-87** [comment]
That's why there are package maintainers, but that should not prevent us from providing a general-use rpm package here on our GitHub release page, as we do provide one for debian-based systems. Can we conclude this topic now?

**Comment by Vascom** [comment]
> Can we conclude this topic now? This is also not the right place to discuss this, BTW.

Yes.

**Comment by Nightwalker-87** [comment]
@chenguokai Can you give it a test again on macOS? I've successfully compiled, installed and used the toolset executables on debian. 
@slyshykO: Linking to libssp-0.dll on windows for cross-build binaries is still non-functional. I've decided not to fix this within this PR any more. It should be addressed separately. I may also leave that to others.

If there are no further significant issues I'd like to merge this PR now. It has become quite bulky already.

**Comment by slyshykO** [comment]
@Nightwalker-87  
Can linnk libssp statically by changing only one line in project
https://github.com/stlink-org/stlink/pull/960/commits/3d34ea5278260d464e015209e0019dd5b2efb945

**Comment by Nightwalker-87** [comment]
> Can link libssp statically by changing only one line in the project

Oh that is good news - I'm surprised it is achievable that easy. I tried that argument somewhere else. Ok - wait let us finish and merge this PR first. Yours should follow subsequently then.

**Comment by slyshykO** [comment]
>  I'm surprised it is achievable that easy. 

Looks easy but I, like you, tried many times before getting success on build :)

**Comment by chenguokai** [comment]
Mostly good with two problems.

1. There are some cmake warnings
```
CMake Warning (dev) at CMakeLists.txt:146:
  Syntax Warning in cmake code at column 59

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
2. cmake failed with with a simple version bump in MacPorts Portfile

```
...
-- Found libusb: /opt/local/lib/libusb-1.0.a  
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for __stack_chk_fail in ssp
-- Looking for __stack_chk_fail in ssp - not found
-- STLINK_LIB_SHARED: stlink
-- PROJECT_VERSION_MAJOR: 
-- VERSION: ..
CMake Error at CMakeLists.txt:167 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


-- STLINK_LIB_STATIC: stlink-static
-- PROJECT_VERSION_MAJOR: 
-- VERSION: ..
CMake Error at CMakeLists.txt:203 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
...
```

The two could not be a problem since I only checked out `dist` branch which could have missed out some commits.

**Comment by Nightwalker-87** [comment]
1) Try:
`execute_process(COMMAND bash -c "export LD_LIBRARY_PATH="${CMAKE_INSTALL_LIBDIR}" ")`
(Note the change a the end!)

2) Here your version numbers were not read correctly, which is the reason why it failed. Git present? Version file present with the correct format? (This is not a big deal though, looks like something local, because I fixed that before.)

**Comment by Nightwalker-87** [comment]
Thank you both @chenguokai & @slyshykO for reviewing this. :1st_place_medal:

**Comment by chenguokai** [comment]
> Try: execute_process(COMMAND bash -c "export LD_LIBRARY_PATH="${CMAKE_INSTALL_LIBDIR}" ") (Note the change a the end!)

Finally I figured out the problem here. Might be a MacPorts specific issue with one cmake flag set like `-DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules"` where the path `/opt/local/share/cmake/Modules` does not exist. I will ask the developers of MacPorts for more information about the path.

**Comment by Nightwalker-87** [comment]
> Edit: Not triggered by this, I forgot to remove my local modification before testing :sweat_smile:

That will likely help... :smile:

**Pull request merged**
