### PR TITLE
option byte support improved

### PR DESCRIPTION
**Pull request by 2a17**

### CODE REVIEW

**Comment by 2a17** [comment]
option byte wirte does not work, parameter is not forwarded

**Comment by 2a17** [comment]
tested on chip id 0x0413

**Comment by 2a17** [comment]
diff:
`diff --git a/src/st-flash/flash_opts.c b/src/st-flash/flash_opts.c
index e74ecc1c..2ef72c12 100644
--- a/src/st-flash/flash_opts.c
+++ b/src/st-flash/flash_opts.c
@@ -337,12 +337,27 @@ int flash_get_opts(struct flash_opts* o, int ac, char** av) {
 
             if (ac == 2) {
                 uint32_t addr;
-                result = get_integer_from_char_array(av[1], &addr);
+                result = get_integer_from_char_array(av[0], &addr);
                 if (result != 0) {
                     return bad_arg ("addr");
                 } else {
                     o->addr = (stm32_addr_t) addr;
                 }
+                uint32_t val;
+                result = get_integer_from_char_array(av[1], &val);
+                if (result != 0) {
+                    return bad_arg ("val");
+                } else {
+                    o->val = (uint32_t) val;
+                }
+            } else {
+                uint32_t val;
+                result = get_integer_from_char_array(av[0], &val);
+                if (result != 0) {
+                    return bad_arg ("val");
+                } else {
+                    o->val = (uint32_t) val;
+                }
             }
         } else if (o->area == FLASH_OPTION_BYTES_BOOT_ADD) { // expect option bytes boot address
             if (ac != 1) { return invalid_args("option bytes boot_add write <value>"); }`

**Comment by 2a17** [comment]
diff --git a/src/st-flash/flash_opts.c b/src/st-flash/flash_opts.c
index e74ecc1c..2ef72c12 100644
--- a/src/st-flash/flash_opts.c
+++ b/src/st-flash/flash_opts.c
@@ -337,12 +337,27 @@ int flash_get_opts(struct flash_opts* o, int ac, char** av) {
 
             if (ac == 2) {
                 uint32_t addr;
-                result = get_integer_from_char_array(av[1], &addr);
+                result = get_integer_from_char_array(av[0], &addr);
                 if (result != 0) {
                     return bad_arg ("addr");
                 } else {
                     o->addr = (stm32_addr_t) addr;
                 }
+                uint32_t val;
+                result = get_integer_from_char_array(av[1], &val);
+                if (result != 0) {
+                    return bad_arg ("val");
+                } else {
+                    o->val = (uint32_t) val;
+                }
+            } else {
+                uint32_t val;
+                result = get_integer_from_char_array(av[0], &val);
+                if (result != 0) {
+                    return bad_arg ("val");
+                } else {
+                    o->val = (uint32_t) val;
+                }
             }
         } else if (o->area == FLASH_OPTION_BYTES_BOOT_ADD) { // expect option bytes boot address
             if (ac != 1) { return invalid_args("option bytes boot_add write <value>"); }

**Comment by Ant-ON** [comment]
@2a17 Yes, сorrections in the right direction. But it is worth paying attention to write code: https://github.com/stlink-org/stlink/blob/cc9bedd13fe79207508ad2cfd95d738ed2babdf0/src/st-flash/flash.c#L182-L193
Parsing needs to be simplify by remove unused parameters (filename and addr)

**Review by Nightwalker-87 — APPROVED** [review]

**Review by Ant-ON — APPROVED** [review]

**Review by Nightwalker-87 — APPROVED** [review]

**Pull request merged**
