### PR TITLE
[doc] Updated documentation on target resetting

### LINKED ISSUE #261: [reset] STM32F030: --reset option is not working
How --reset switch is expected to work ?
Enable --reset doesn't have any impact on board.
On oscilloscope there is no pull-down for RESET line.
$ st-flash --reset write stm32f030_lab.bin 0x8000000
2014-09-01T19:56:13 INFO src/stlink-common.c: Loading device parameters....
2014-09-01T19:56:13 INFO src/stlink-common.c: Device connected is: F0 small device, id 0x10006444
2014-09-01T19:56:13 INFO src/stlink-common.c: SRAM size: 0x1000 bytes (4 KiB), Flash: 0x4000 bytes (16 KiB) in pages of 1024 bytes
2014-09-01T19:56:13 INFO src/stlink-common.c: Attempting to write 3008 (0xbc0) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000800 erased
2014-09-01T19:56:13 INFO src/stlink-common.c: Finished erasing 3 pages of 1024 (0x400) bytes
2014-09-01T19:56:13 INFO src/stlink-common.c: Starting Flash write for VL/F0 core id
2014-09-01T19:56:13 INFO src/stlink-common.c: Successfully loaded flash loader in sram
  2/2 pages written
2014-09-01T19:56:13 INFO src/stlink-common.c: Starting verification of write complete
2014-09-01T19:56:13 INFO src/stlink-common.c: Flash written and verified! jolly good!

### PR DESCRIPTION
**Pull request by Ant-ON**
Updated a target resetting documentation. Related with #220, #1012

(Closes #261)

### CODE REVIEW

**Review by Nightwalker-87 — APPROVED** [review]

**Comment by Nightwalker-87** [comment]
@Ant-ON: Sorry for asking, but can you rebase this PR to an earlier commit without closing it?
I'm currently trying to fix the Travis CI build issue we're facing currently.
This would allow for e.g. a force push without killing the base of this PR.

**Comment by Ant-ON** [comment]
@Nightwalker-87 I cannot do rebase, I can merge changes from develop.

**Comment by Nightwalker-87** [comment]
OK, wait - that will not help to preserve consistency in history for this PR.
I'll have a look this evening. Following git documentation, it should be possible to rebase to the current `develop`.

**Comment by Ant-ON** [comment]
@Nightwalker-87 I rebase this PR to `develop`

**Comment by Nightwalker-87** [comment]
Found out how-to?

**Comment by Nightwalker-87** [comment]
@Ant-ON Are there any tickets of which one can be sure of that they are resolved with this PR?

**Pull request merged**
