### PR TITLE
Use vl flashloader for all STMF1 series

### PR DESCRIPTION
**Pull request by Ant-ON**
stlink_write_flash should use the flashloader for all chip of F1 series. But there are problems in stlink_flash_loader_write_to_sram. Not all chip IDs are associated with the flashloader. It fixes issue #1041.

### CODE REVIEW

**Review by Nightwalker-87 — APPROVED** [review]

**Comment by Nightwalker-87** [comment]
@Ant-ON: Can yo please rebase this PR to the develop branch without closing and reopening it.
There are various problems in the nightly tree which need to be fixed. We don't want these in our development tree.
I advise to stay on develop for now.

**Comment by Ant-ON** [comment]
@Nightwalker-87, I cannot find how to move/rebase a commit from one branch to another. It can only be copied ...
ps The night tree has some useful patches, but a bit of garbage

**Comment by stappersg** [comment]
On Tue, Sep 29, 2020 at 08:34:04AM -0700, Anton wrote:
> I cannot find how to move/rebase a commit from one branch to another. It can only be copied ...


You are free to do git stuff outside of github.com.


With `git format-patch` you get seperate commits.

With `git am` you can apply those commits.

**Comment by Nightwalker-87** [comment]
@Ant-ON: I know - thats why I don't want it to be merged into develop. Instead I'll do some local maintenance on it.

**Comment by Nightwalker-87** [comment]
@Ant-ON: Try this: https://stackoverflow.com/questions/44664830/how-can-you-change-the-branch-on-a-pr

**Comment by Ant-ON** [comment]
@Nightwalker-87 
Yes, but I have not found how to change the current PR.
I realized that this is not possible.

**Comment by Nightwalker-87** [comment]
@Ant-ON: I recommend you to delete this `nightly` branch on your fork as well as it fails completely on our automated build tests (which I noticed too late). Some merges to that branch did mix up destructively and it appears too complicated to unwind the issues again.

**Comment by Ant-ON** [comment]
@Nightwalker-87 I removed this branch from my fork

**Pull request closed without merging**
