### PR TITLE
st-util: removed now useless v1/v2 STLink version stuff

### PR DESCRIPTION
**Pull request by grevaillot**
well, not needed anymore.

### CODE REVIEW

**Comment by grevaillot** [comment]
nb: st-util probe mentions the not so documented probe filter thingie using 

> ￼        "The STLINKv2 device to use can be specified in the environment\n"		￼        "The STLINK device to use can be specified in the environment\n"
> ￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"		￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"

this should probably be documented somewhere in the documentation or in other tools commandline help.

**Comment by Nightwalker-87** [comment]
> nb: st-util probe mentions the not so documented probe filter thingie using
> 
> > ￼        "The STLINKv2 device to use can be specified in the environment\n"		￼        "The STLINK device to use can be specified in the environment\n"
> > ￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"		￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"
> 
> this should probably be documented somewhere in the documentation or in other tools commandline help.

I think it should go to` /doc/man/st-util.md` as well, but as I can see the stuff there seems outdated as well and does not match the output of `st-util --help` anymore ... :disappointed:

**Comment by Nightwalker-87** [comment]
@grevaillot: Could you add the doc part to this PR as well, so that we have it all together? That would be great.

**Comment by grevaillot** [comment]
I'll have a look

**Comment by grevaillot** [comment]
> > nb: st-util probe mentions the not so documented probe filter thingie using
> > > ￼        "The STLINKv2 device to use can be specified in the environment\n"		￼        "The STLINK device to use can be specified in the environment\n"
> > > ￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"		￼        "variable STLINK_DEVICE on the format <USB_BUS>:<USB_ADDR>.\n"
> > 
> > 
> > this should probably be documented somewhere in the documentation or in other tools commandline help.
> 
> I think it should go to` /doc/man/st-util.md` as well, but as I can see the stuff there seems outdated as well and does not match the output of `st-util --help` anymore ...

actually these env variables are used in all tools - these are checked in the probe code .. So, all doc need to be updated :)

**Comment by Nightwalker-87** [comment]
We also have /doc/man/st-info.md and /doc/man/st-flash.md ;-)
... but I can't find any related stuff in our tutorial where it would fit in well. :confused:

**Comment by grevaillot** [comment]
probe filter might not really be needed in tutorial i think. I updated the doc to remove the version filter and to mention the --serial parameter where STLINK_DEVICE is mentionned tool

**Comment by slyshykO** [comment]
@grevaillot Congrat 🎉

**Pull request merged**
